name: Run my Playwright tests

on:
  push: 
    branches:
      - main

jobs:
  Playwright_Test_1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo or basically cloning the repo into github runner workspace
        uses: actions/checkout@v4
      - name: Setup Node JS
        uses: actions/setup-node@v4
      - name: Install Playwright Dependencies as per package-lock.jsom
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run the Test1
        run: npx playwright test Test1.spec.js
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report
            test-results
